# Generated by Django 4.1.3 on 2022-11-23 17:50

from django.db import migrations, models
import image_upload.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="",
                        validators=[
                            image_upload.validators.validate_image_extension,
                            image_upload.validators.validator,
                            image_upload.validators.validate_image_size,
                        ],
                        verbose_name="Uploaded image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, editable=False, null=True, upload_to="thumbnails"
                    ),
                ),
                (
                    "thumbnail_premium",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="thumbnails_premium",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
